### PR TITLE
Add environment option to logger

### PR DESCRIPTION
**Pull request by JBonwick**
## Overview
- [x] I have performed a self review of my code
- [x] I have made corresponding changes to the documentation
- [ ] I have commented my code, particularly in hard-to-understand areas

- [ ] New and existing tests pass locally with my changes
- [ ] The code modified as part of this PR has been covered with tests

### Problem statement
The environment variable is not currently set when sending logs.

### Solution
A new variable has been added to capture the environement.

### Dependencies
N/A

### Test procedures
N/A

### Links

JIRA: https://netsells.atlassian.net/browse/INT-706

### Migrations
No

### Environment variables
N/A

### Deployment notes
N/A

### CODE REVIEW

**Comment by JBonwick** [comment]
@spamoom I've currently defaulted the environment to null to keep this as framework agnostic as possible, the alternative being we default it to the env variable e.g. `env('APP_ENV', null)`.

**Comment by spamoom** [comment]
@JBonwick don't forget you changed the file called LaravelLogger.php - you could set the default to APP_ENV and override with the config if it's set?

**Comment by JBonwick** [comment]
> @JBonwick don't forget you changed the file called LaravelLogger.php - you could set the default to APP_ENV and override with the config if it's set?

@spamoom ah good point, i'll update to include that.

**Review by spamoom — APPROVED** [review]

**Comment by spamoom** [comment]
Good to tag and bag @JBonwick

**Pull request merged**
